### ISSUE TITLE
Issue with RuntimeError: new_Decoder returned -1

### ISSUE THREAD

**Issue by priyablue** [gorinars/ros_voice_control#2]
while running  python file ros_voice_control.py. Can you please let me know if there is any i have missed. 

Pasting the error message

ERROR: "dict.c", line 195: Line 1: Phone 'B' is mising in the acoustic model; word 'BACK' ignored
ERROR: "dict.c", line 195: Line 2: Phone 'F' is mising in the acoustic model; word 'FORWARD' ignored
ERROR: "dict.c", line 195: Line 3: Phone 'F' is mising in the acoustic model; word 'FULL' ignored
ERROR: "dict.c", line 195: Line 4: Phone 'HH' is mising in the acoustic model; word 'HALF' ignored
ERROR: "dict.c", line 195: Line 5: Phone 'L' is mising in the acoustic model; word 'LEFT' ignored
ERROR: "dict.c", line 195: Line 6: Phone 'M' is mising in the acoustic model; word 'MOVE' ignored
ERROR: "dict.c", line 195: Line 7: Phone 'R' is mising in the acoustic model; word 'RIGHT' ignored
ERROR: "dict.c", line 195: Line 8: Phone 'S' is mising in the acoustic model; word 'SPEED' ignored
ERROR: "dict.c", line 195: Line 9: Phone 'S' is mising in the acoustic model; word 'STOP' ignored
INFO: dict.c(213): Allocated 0 KiB for strings, 0 KiB for phones
INFO: dict.c(336): 0 words read
INFO: dict2pid.c(396): Building PID tables for dictionary
INFO: dict2pid.c(406): Allocating 34^3 * 2 bytes (76 KiB) for word-initial triphones
INFO: dict2pid.c(132): Allocated 28016 bytes (27 KiB) for word-final triphones
INFO: dict2pid.c(196): Allocated 28016 bytes (27 KiB) for single-phone word triphones
INFO: kws_search.c(423): KWS(beam: -1080, plp: -23, default threshold 0, delay 10)
ERROR: "kws_search.c", line 174: The word 'BACK' is missing in the dictionary
ERROR: "kws_search.c", line 174: The word 'FORWARD' is missing in the dictionary
ERROR: "kws_search.c", line 174: The word 'FULL' is missing in the dictionary
ERROR: "kws_search.c", line 174: The word 'HALF' is missing in the dictionary
ERROR: "kws_search.c", line 174: The word 'LEFT' is missing in the dictionary
ERROR: "kws_search.c", line 174: The word 'MOVE' is missing in the dictionary
ERROR: "kws_search.c", line 174: The word 'RIGHT' is missing in the dictionary
ERROR: "kws_search.c", line 174: The word 'STOP' is missing in the dictionary
Traceback (most recent call last):
  File "voice_control.py", line 134, in <module>
    ASRControl(args.model, args.lexicon, args.kwlist, args.rospub)
  File "voice_control.py", line 49, in __init__
    self.decoder = Decoder(config)
  File "/usr/lib/python2.7/dist-packages/pocketsphinx/pocketsphinx.py", line 332, in __init__
    this = _pocketsphinx.new_Decoder(*args)
RuntimeError: new_Decoder returned -1

**Comment by vivekagra** [comment]
Hi, Did you find a solution to this issue?

**Comment by gorinars** [comment]
Sorry folks, this project was quite abandoned recently. Unless you want to stick to sphinx decoder, I would suggest looking at https://github.com/alphacep/ros-vosk
It should be more accurate and overall better maintained
